project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: true
pull_request_title: "chore(i18n): sync translations from Crowdin"

files:
  - source: /src/locales/en/common.json
    translation: /src/locales/%two_letters_code%/common.json
